[{'item': {'name': 'lum-berry', 'url': 'https://pokeapi.co/api/v2/item/134/'},
  'version_details': [{'rarity': 100,
    'version': {'name': 'ruby',
     'url': 'https://pokeapi.co/api/v2/version/7/'}},
   {'rarity': 100,
    'version': {'name': 'sapphire',
     'url': 'https://pokeapi.co/api/v2/version/8/'}},
   {'rarity': 100,
    'version': {'name': 'emerald',
     'url': 'https://pokeapi.co/api/v2/version/9/'}},
   {'rarity': 100,
    'version': {'name': 'diamond',
     'url': 'https://pokeapi.co/api/v2/version/12/'}},
   {'rarity': 100,
    'version': {'name': 'pearl',
     'url': 'https://pokeapi.co/api/v2/version/13/'}},
   {'rarity': 100,
    'version': {'name': 'platinum',
     'url': 'https://pokeapi.co/api/v2/version/14/'}},
   {'rarity': 100,
    'version': {'name': 'heartgold',
     'url': 'https://pokeapi.co/api/v2/version/15/'}},
   {'rarity': 100,
    'version': {'name': 'soulsilver',
     'url': 'https://pokeapi.co/api/v2/version/16/'}},
...
    'version': {'name': 'ultra-sun',
     'url': 'https://pokeapi.co/api/v2/version/29/'}},
   {'rarity': 5,
    'version': {'name': 'ultra-moon',
     'url': 'https://pokeapi.co/api/v2/version/30/'}}]}]